# Generated by Django 3.2.15 on 2022-09-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220902_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipe/images/', verbose_name='Фото рецепта'),
        ),
    ]
